var sqlite3 = require('sqlite3').verbose();
let db = new sqlite3.Database('./portfolio.db');

db.serialize(() => {

    db.run(`insert or ignore into ticker_table (ticker_text, ticker_co)
        values ('INTC', 'INTEL CORPORATION'),
       ('ISRG', 'INTUITIVE SURGICAL, INC.'),
       ('MDT', 'MEDTRONIC PUBLIC LIMITED COMPANY'),
       ('SYK', 'STRYKER CORPORATION'),
       ('VOO', 'Vanguard 500 Idx;ETF'),
       ('AMD', 'ADVANCED MICRO DEVICES, INC.'),
       ('BABA', 'Alibaba Group Holding Limited'),
       ('ALGN', 'ALIGN TECHNOLOGY, INC.'),
       ('GOOG', 'ALPHABET INC.'),
       ('AAPL', 'APPLE INC.'),
       ('AMAT', 'APPLIED MATERIALS, INC.'),
       ('AVGO', 'BROADCOM INC.'),
       ('BEP', 'Biomass Energy Project S.A.'),
       ('CSCO', 'CISCO SYSTEMS, INC.'),
       ('CRWD', 'CROWDSTRIKE HOLDINGS, INC.'),
       ('LLY', 'ELI LILLY AND COMPANY'),
       ('FTNT', 'FORTINET, INC.'),
       ('KTB', 'Kontoor Brands, Inc.'),
       ('ODD', 'ODDITY TECH LTD'),
       ('PYPL', 'PAYPAL HOLDINGS, INC.'),
       ('RDDT', 'REDDIT INC.'),
       ('RUN', 'SUNRUN INC.'),
       ('TXN', 'TEXAS INSTRUMENTS INCORPORATED'),
       ('VFC', 'V.F. CORPORATION'),
       ('VWDRY', 'Vestas Wind Systems A/S'),
       ('WM', 'WASTE MANAGEMENT, INC.'),
       ('ABBV', 'ABBVIE INC.'),
       ('AGYS', 'AGILYSYS, INC.'),
       ('AXP', 'AMERICAN EXPRESS COMPANY'),
       ('ANET', 'ARISTA NETWORKS, INC.'),
       ('AZN', 'ASTRAZENECA PLC'),
       ('T', 'AT&T INC.'),
       ('BAC', 'BANK OF AMERICA CORPORATION'),
       ('BA', 'THE BOEING COMPANY'),
       ('KO', 'THE COCA-COLA COMPANY'),
       ('CPRT', 'COPART, INC.'),
       ('DHI', 'D.R. HORTON, INC.'),
       ('UUUU', 'ENERGY FUELS INCORPORATED'),
       ('XOM', 'EXXON MOBIL CORPORATION'),
       ('FISV', 'FISERV, INC.'),
       ('GD', 'GENERAL DYNAMICS CORPORATION'),
       ('IRM', 'IRON MOUNTAIN INCORPORATED'),
       ('KMI', 'KINDER MORGAN, INC.'),
       ('MRK', 'MERCK & CO., INC.'),
       ('MSFT', 'MICROSOFT CORPORATION'),
       ('NGD', 'NEW GOLD INC.'),
       ('NVDA', 'NVIDIA CORPORATION'),
       ('SSO', 'ProShares:Ultra S&P500'),
       ('RTX', 'RTX CORPORATION'),
       ('CRM', 'SALESFORCE, INC.'),
       ('SLG', 'SL GREEN REALTY CORP.'),
       ('SDY', 'SS SPDR S&P Dividend'),
       ('VDC', 'Vanguard Cnsmr Stp;ETF'),
       ('VNQ', 'Vanguard RE Idx;ETF'),
       ('VWO', 'Vanguard EM St I;ETF'),
       ('WFC', 'WELLS FARGO & COMPANY'),
       ('C', 'CITIGROUP INC.'),
       ('GLNCY', 'GLENCORE PLC'),
       ('GRAL', 'GRAIL, INC.'),
       ('ICLR', 'ICON PUBLIC LIMITED COMPANY'),
       ('ILMN', 'ILLUMINA, INC.'),
       ('MU', 'MICRON TECHNOLOGY, INC.'),
       ('NVO', 'Novo Nordisk A/S'),
       ('SLB', 'SLB N.V.'),
       ('TSM', 'Taiwan Semiconductor Manufacturing Co., Ltd.'),
       ('TSLA', 'TESLA, INC.'),
       ('TTI', 'TETRA TECHNOLOGIES, INC.'),
       ('VEON', 'VEON Ltd.'),
       ('WMT', 'WALMART INC.'),
       ('LMT', 'LOCKHEED MARTIN CORPORATION'),
       ('AES', 'THE AES CORPORATION'),
       ('CLH', 'CLEAN HARBORS, INC.'),
       ('EOSE', 'EOS ENERGY ENTERPRISES, INC.'),
       ('FSLR', 'FIRST SOLAR, INC.'),
       ('GRRR', 'Gorilla Technology Group Inc.'),
       ('KULR', 'KULR TECHNOLOGY GROUP, INC.'),
       ('LAC', 'Lithium Americas Corp'),
       ('NXT', 'Nextpower Inc.'),
       ('PSN', 'PARSONS CORPORATION'),
       ('XYL', 'XYLEM INC.'),
       ('TOTZF', 'TOTAL ENERGY SERVICES INC.')`);

});